---
title: 'Post #5: State Level Predictions'
author: Avi Agarwal
date: '2024-10-07'
slug: post-5-state-level-predictions
categories: []
tags: []
---
```{r , echo= FALSE, message = FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(sjPlot)
library(car)
library(caret)
library(CVXR)
library(foreign)
library(glmnet)
library(haven)
library(janitor)
library(kableExtra)
library(maps)
library(mlr3)
library(randomForest)
library(ranger)
library(RColorBrewer)
library(sf)
library(viridis)
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
pop_vote <- read_csv("popvote_1948-2020.csv")
pop_vote1 <- pop_vote |>
  select(year,party,pv2p,incumbent_party, juneapp)|> 
  filter(party == "democrat") 
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
nat_polls <- read_csv("national_polls_1968-2024.csv")
nat_polls_dem <- nat_polls |>
  filter(party == "DEM") |>
  group_by(year, weeks_left) |>
  summarize(avg_poll = mean(poll_support)) |> 
  filter(weeks_left < 15 & weeks_left >= 5) |>
  pivot_wider(names_from = weeks_left,
              values_from = avg_poll ) |>
  left_join(pop_vote1, by = "year") 
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
week_polls_model <- lm(pv2p ~ `14` + `13` + `12` + `11` + `10` + `9` + `8` + `7` + `6` + `5`, data = nat_polls_dem)
coefficients <- week_polls_model$coefficients[-1]
weights <- coefficients / sum(coefficients)

weighted_polling <- nat_polls_dem |>
  mutate(weighted_avg_poll = `14` * weights[1] + `13` * weights[2] +
                              `12` * weights[3] + `11` * weights[4] + 
                              `10` * weights[5] + `9` * weights[6] + 
                              `8` * weights[7] + `7` * weights[8] + 
                              `6` * weights[9] + `5` * weights[10]) |>
  select(year, pv2p, incumbent_party, weighted_avg_poll, juneapp)
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
fred_econ <- read_csv("fred_econ.csv") 
fred_adjusted <- fred_econ |>
  filter(year > 1958) |>
  mutate(unemployment_growth_quarterly = (unemployment - lag(unemployment, 1)) / lag(unemployment, 1) * 100) |>
  filter(quarter == 2) |>
  mutate(RDPI_growth_annually = (RDPI - lag(RDPI, 1)) / lag(RDPI, 1) * 100) |> 
  mutate(sp500_growth_quarterly = ((sp500_adj_close - sp500_open)) / sp500_open * 100) |>
  mutate(sp500_growth_anually = (sp500_adj_close - lag(sp500_adj_close, 1)) / lag(sp500_adj_close, 1) * 100) |> 
  mutate(unemployment_growth_anually = (unemployment - lag(unemployment, 1)) / lag(unemployment, 1) * 100) |>
  filter(year >= 1960 & year != 2020 & year %% 4 == 0) |> #exclude 2020 since it such an outlier
  select(year, RDPI_growth_quarterly, GDP_growth_quarterly)

```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
model_one_data <- weighted_polling |>
  left_join(fred_adjusted, by = "year") |> 
  mutate(incumbent_party = ifelse(incumbent_party == "TRUE", 1, 0)) 
model_one_data_p <- model_one_data |> 
  filter(year > 2020)
model_one_data_r <- model_one_data |> 
  filter(year < 2020)
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
model_one <- lm(pv2p ~ weighted_avg_poll + RDPI_growth_quarterly + incumbent_party, data = model_one_data_r)

```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
pred_model_one <- predict(model_one, model_one_data_p, interval = "prediction")
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
pred_model_one_df <- as.data.frame(pred_model_one)
colnames(pred_model_one_df) <- c("Prediction", "Lower Bound", "Upper Bound")
pred_model_one_df <- data.frame( #Used ChatGPT to add % signs and use sjPLot
  Prediction = sprintf("%.2f%%", pred_model_one_df$Prediction),
  `Lower Bound` = sprintf("%.2f%%", pred_model_one_df$`Lower Bound`),
  `Upper Bound` = sprintf("%.2f%%", pred_model_one_df$`Upper Bound`)
)

nat_model <- tab_model(model_one, 
                               show.se = TRUE,
                               title = "Including Incumbent Regression Results", 
                               dv.labels = "Democrat Two Party Vote Share",  
                               pred.labels = c("Weighted Avg. Poll", "RDPI Growth Quarterly", "Incumbent Party"))

nat_pred <- tab_df(pred_model_one_df, 
       title = "2024 Democrat Two Party Vote Share via Model Including Incumbent Party",
       show.rownames = FALSE)
```


```{r, echo= FALSE, message = FALSE, warning=FALSE}
rf_model_data <- weighted_polling |>
  left_join(fred_adjusted, by = "year") |> 
  mutate(incumbent_party = ifelse(incumbent_party == "TRUE", 1, 0))

rf_model_data_r <- rf_model_data |> filter(year < 2020)
rf_model_data_p <- rf_model_data |> filter(year == 2024)

train_data <- rf_model_data_r |> 
  select(pv2p, weighted_avg_poll, RDPI_growth_quarterly, incumbent_party)

predict_data <- rf_model_data_p |>
  select(weighted_avg_poll, RDPI_growth_quarterly, incumbent_party)

n_features <- ncol(train_data) - 1

rf_fit <- ranger(
  pv2p ~ ., 
  data = train_data, 
  mtry = floor(n_features / 3), 
  respect.unordered.factors = "order", 
  seed = 02138, 
  classification = FALSE
)

rf_predictions <- predict(rf_fit, data = predict_data)$predictions

pred_model_rf_df <- data.frame(
  year = 2024,
  Prediction = sprintf("%.2f%%", rf_predictions)
)

rf_nat_pred <- tab_df(pred_model_rf_df, 
       title = "2024 Democrat Two Party Vote Share via Random Forest Model",
       show.rownames = FALSE)
```



```{r , echo= FALSE, message = FALSE, warning=FALSE}
swing_states <- c("Arizona", "Georgia", "Michigan", "Nevada", "North Carolina", "Pennsylvania", "Wisconsin")
swing_state_polls <- read_csv("state_polls_1968-2024.csv") |>
  filter(state %in% swing_states & weeks_left < 15 & weeks_left >= 5 & party == "DEM") |>
  group_by(year, state) |>
  summarize(avg_poll_14_9 = mean(poll_support[weeks_left <= 14 & weeks_left >= 9]),
    avg_poll_8_5 = mean(poll_support[weeks_left < 9 & weeks_left >= 5]))
```

```{r, echo= FALSE, message = FALSE, warning=FALSE}
state_pop_vote <- read.csv("state_popvote_1948_2020.csv") |>
  mutate(pv2p = D_pv2p)
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
swing_model_data <- swing_state_polls |>
  left_join(fred_adjusted, by = "year") |> 
  left_join(pop_vote1, by = "year") |>
  select(-pv2p) |>
  left_join(state_pop_vote, by = c("year", "state")) |>
  mutate(incumbent_party = ifelse(incumbent_party == "TRUE", 1, 0))

```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
swing_model_data_r <- swing_model_data |> filter(year < 2020)
swing_model_data_p <- swing_model_data |> filter(year == 2024)

lm_swing_model <- lm(pv2p ~ avg_poll_8_5 + state + RDPI_growth_quarterly + incumbent_party, data = swing_model_data_r)

pred_lm_swing_model <- predict(lm_swing_model, swing_model_data_p, interval = "prediction")

```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
pred_lm_swing_model_df <- as.data.frame(pred_lm_swing_model)
colnames(pred_lm_swing_model_df) <- c("Prediction", "Lower Bound", "Upper Bound")

state_model_lm <- tab_model(lm_swing_model, 
                          show.se = TRUE,
                          title = "Linear Model Results for Swing States",
                          dv.labels = "Democrat Two Party Vote Share",  
                          pred.labels = c("intercept", "Avg Poll Weeks 8-5", "state", "RDPI Growth Quarterly", "Incumbent Party"))

pred_lm_swing_model_df <- data.frame(
  state = swing_model_data_p$state,
  year = 2024,
  Prediction = sprintf("%.2f%%", pred_lm_swing_model_df$Prediction),
  `Lower Bound` = sprintf("%.2f%%", pred_lm_swing_model_df$`Lower Bound`),
  `Upper Bound` = sprintf("%.2f%%", pred_lm_swing_model_df$`Upper Bound`)
)

lm_swing_pred <- tab_df(pred_lm_swing_model_df, 
       title = "2024 Democrat Two Party Vote Share via Linear Model in Swing States",
       show.rownames = FALSE)
```



```{r , echo= FALSE, message = FALSE, warning=FALSE}

swing_train_data <- swing_model_data_r |> 
  select(pv2p, state, avg_poll_8_5, RDPI_growth_quarterly, incumbent_party)

swing_predict_data <- swing_model_data_p |> 
  select(avg_poll_8_5,state, RDPI_growth_quarterly, incumbent_party)

n_swing_features <- ncol(swing_train_data) - 1

rf_swing_fit <- ranger(
  pv2p ~ ., 
  data = swing_train_data, 
  mtry = floor(n_swing_features / 3), 
  respect.unordered.factors = "order", 
  seed = 02138, 
  classification = FALSE
)

rf_swing_predictions <- predict(rf_swing_fit, data = swing_predict_data)$predictions

swing_pred_model_rf_df <- data.frame(
  state = swing_model_data_p$state,
  year = 2024,
  Prediction = sprintf("%.3f%%", rf_swing_predictions)
)

rf_swing_preds <- tab_df(swing_pred_model_rf_df, 
       title = "2024 Democrat Two Party Vote Share via Random Forest Model in Swing States",
       show.rownames = FALSE)
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
nat_model
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
nat_pred
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
rf_nat_pred
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
state_model_lm
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
lm_swing_pred
```

```{r , echo= FALSE, message = FALSE, warning=FALSE}
rf_swing_preds
```

